import * as functions from "firebase-functions";
import express from "express";
import cors from "cors";
import accountRouter from "./routes/accountRouter";
import reviewRouter from "./routes/reviewRouter";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/accounts", accountRouter);
app.use("/reviews", reviewRouter);
export const api = functions.https.onRequest(app);
